size_t StrLen(const char *str);
int StrCmp(const char *str1, const char *str2);
char *StrCpy(char *dest, const char *src);
char *StrnCpy(char *dest, const char *src, size_t n);
int StrnCmp(const char *str1, const char *str2, size_t n);
int StrcaseCmp(const char *str1, const char *str2);
char *StrChr(const char *str, int c);
char *StrDup(char *src);
char *StrCat(char *dest, const char *src);
char *StrnCat(char *dest, const char *src, size_t num);
char *StrStr(const char *haystack, const char *needle);
size_t StrSpn(const char *s, const char *accept);
int IsPalindrome(char *str);
